-- ============================================================
-- GS08 - Matriculas y Notas | 01-schema.sql
-- DDL PostgreSQL 16 traducido de legacy/script.sql.txt (MySQL 8.x)
-- Autor: @analista | Fecha: 21/09/2026 | Sprint 0
--
-- Lo ejecuta el entrypoint de la imagen postgres (docker-entrypoint-initdb.d)
-- UNA sola vez, al crear el volumen pgdata, contra la base POSTGRES_DB
-- (gs08_matriculas). En el cluster de Kubernetes el DDL lo aplica Alembic
-- (Job gs08-migraciones); este archivo es el esquema base y la referencia.
--
-- Convenciones de la traduccion (detalle y justificacion: docs/analisis/modelo-datos.md):
--   * TINYINT(1) 1/0           -> boolean
--   * INT UNSIGNED AUTO_INCREMENT -> integer GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT, no ALWAYS: permite cargar los ids del seed y de la migracion de datos)
--   * TIMESTAMP DEFAULT CURRENT_TIMESTAMP -> timestamptz DEFAULT now()
--     (mismo instante, pero con zona horaria: el legacy guardaba hora local sin zona)
--   * ENGINE=InnoDB / COLLATE      -> no aplica: PostgreSQL solo tiene utf8 (UTF8)
--   * Las validaciones que el legacy hacia en PHP se suben a CHECK/UNIQUE
--     (la BD es la ultima linea de defensa; la API las repite para dar 422 con mensaje)
-- ============================================================

SET client_encoding = 'UTF8';

-- ------------------------------------------------------------
-- REQUISITO DE ESQUEMA: unaccent
-- El buscador del legacy (MySQL, collation utf8mb4_unicode_ci) encontraba
-- "huaman" buscando "Huamán" porque la collation ignora tildes. PostgreSQL no:
-- hay que usar unaccent(...) para cumplir el criterio C-08 (misma cantidad de
-- filas con huaman / Huamán / HUAMAN).
-- Va aqui y no en 04-notas.sql a proposito: es requisito del esquema base.
-- La revision inicial de Alembic (D-14) DEBE incluir esta misma linea:
--   op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
-- Requiere superusuario; el usuario de la imagen postgres (POSTGRES_USER) lo es.
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ------------------------------------------------------------
-- TABLA: usuarios  (autenticacion del sistema)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id              integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  varchar(50)  NOT NULL,
    email           varchar(100) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    nombre_completo varchar(100) NOT NULL,
    rol             varchar(20)  NOT NULL DEFAULT 'admin',
    estado          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_usuarios_nombre_usuario UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuarios_email          UNIQUE (email),
    CONSTRAINT ck_usuarios_rol            CHECK (rol IN ('admin', 'asistente')),
    CONSTRAINT ck_usuarios_usuario_formato
        CHECK (nombre_usuario ~ '^[A-Za-z0-9_.]{3,50}$'),
    CONSTRAINT ck_usuarios_email_formato
        CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT ck_usuarios_nombre_no_vacio CHECK (btrim(nombre_completo) <> '')
);

COMMENT ON TABLE  usuarios IS 'Usuarios del sistema administrativo (login del panel)';
COMMENT ON COLUMN usuarios.rol    IS 'admin | asistente';
COMMENT ON COLUMN usuarios.estado IS 'true=activo, false=inactivo (no se puede desactivar el propio usuario)';

-- ------------------------------------------------------------
-- TABLA: estudiantes
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estudiantes (
    id               integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           varchar(20)  NOT NULL,
    dni              char(8)      NOT NULL,
    nombres          varchar(80)  NOT NULL,
    apellidos        varchar(80)  NOT NULL,
    email            varchar(100) NULL,
    telefono         varchar(20)  NULL,
    fecha_nacimiento date         NULL,
    direccion        varchar(150) NULL,
    estado           boolean      NOT NULL DEFAULT true,
    creado_en        timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_estudiantes_codigo UNIQUE (codigo),
    CONSTRAINT uq_estudiantes_dni    UNIQUE (dni),
    CONSTRAINT ck_estudiantes_dni    CHECK (dni ~ '^[0-9]{8}$'),
    CONSTRAINT ck_estudiantes_codigo_no_vacio  CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_estudiantes_nombres_no_vacio  CHECK (btrim(nombres) <> ''),
    CONSTRAINT ck_estudiantes_apellidos_no_vacio CHECK (btrim(apellidos) <> ''),
    CONSTRAINT ck_estudiantes_email
        CHECK (email IS NULL OR email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT ck_estudiantes_fecha_nacimiento
        CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento > DATE '1900-01-01')
);

-- El legacy solo indexaba apellidos (MySQL crea indice implicito en cada UNIQUE).
-- Se agregan indices que el legacy no tenia porque las consultas del API ordenan
-- y buscan tambien por nombres (listado de estudiantes, selector de matriculas).
CREATE INDEX IF NOT EXISTS idx_estudiantes_apellidos ON estudiantes (apellidos);
CREATE INDEX IF NOT EXISTS idx_estudiantes_nombres   ON estudiantes (nombres);

COMMENT ON COLUMN estudiantes.dni   IS '8 digitos, unico (RN-04)';
COMMENT ON COLUMN estudiantes.estado IS 'true=activo (aparece en selectores), false=inactivo (baja logica)';

-- ------------------------------------------------------------
-- TABLA: cursos
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cursos (
    id          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(20)  NOT NULL,
    nombre      varchar(100) NOT NULL,
    descripcion text         NULL,
    creditos    smallint     NOT NULL DEFAULT 3,
    horas       smallint     NOT NULL DEFAULT 48,
    estado      boolean      NOT NULL DEFAULT true,
    creado_en   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_cursos_codigo UNIQUE (codigo),
    CONSTRAINT ck_cursos_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_cursos_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_cursos_creditos CHECK (creditos BETWEEN 1 AND 10),
    CONSTRAINT ck_cursos_horas    CHECK (horas BETWEEN 1 AND 1000)
);

COMMENT ON COLUMN cursos.creditos IS '1..10 (regla del legacy cursos/create.php)';
COMMENT ON COLUMN cursos.horas    IS 'horas lectivas del curso, entero positivo';

-- ------------------------------------------------------------
-- TABLA: matriculas  (relacion N:M entre estudiantes y cursos)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matriculas (
    id              integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id   integer     NOT NULL,
    curso_id        integer     NOT NULL,
    periodo         varchar(7)  NOT NULL,
    fecha_matricula date        NOT NULL,
    estado          varchar(15) NOT NULL DEFAULT 'activa',
    creado_en       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_matriculas_estudiante
        FOREIGN KEY (estudiante_id) REFERENCES estudiantes (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_matriculas_curso
        FOREIGN KEY (curso_id) REFERENCES cursos (id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT uq_matriculas_estudiante_curso_periodo
        UNIQUE (estudiante_id, curso_id, periodo),
    CONSTRAINT ck_matriculas_periodo CHECK (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_matriculas_estado  CHECK (estado IN ('activa', 'retirado'))
);

-- En MySQL el indice de cada FK lo crea el motor. PostgreSQL NO: sin estos dos
-- indices, borrar un estudiante o un curso recorre la tabla completa.
CREATE INDEX IF NOT EXISTS idx_matriculas_estudiante ON matriculas (estudiante_id);
CREATE INDEX IF NOT EXISTS idx_matriculas_curso      ON matriculas (curso_id);
CREATE INDEX IF NOT EXISTS idx_matriculas_periodo    ON matriculas (periodo);
-- Listado por defecto del API: ORDER BY fecha_matricula DESC, estudiante
CREATE INDEX IF NOT EXISTS idx_matriculas_fecha      ON matriculas (fecha_matricula DESC, id DESC);

COMMENT ON TABLE  matriculas IS 'Matriculas: un estudiante en un curso, en un periodo (RN-08)';
COMMENT ON COLUMN matriculas.periodo IS 'AAAA-MM, ej. 2026-02 (RN-06)';
COMMENT ON COLUMN matriculas.estado  IS 'activa | retirado (baja logica de la matricula, RN-07)';
