-- ============================================================
-- GS08 - Matriculas y Notas | 04-notas.sql
-- Notas por matricula: tabla notas + vista v_notas_detalle
-- Autor: @analista | T1.5 | Decision D-01
--
-- ADITIVO: no toca ninguna de las 4 tablas del legacy (usuarios, estudiantes,
-- cursos, matriculas); solo agrega. Verificado con `bash db/verificacion/ejecutar_verificacion.sh`.
--
-- Reglas que se aplican aqui (docs/analisis/modelo-datos.md §3):
--   RN-14  no se registran notas de una matricula retirada (D-06) -> trigger, ERRCODE 23514
--   RN-16  nota 0..20, tipo practica|parcial|final, numero >= 1, unica por (matricula, tipo, numero)
--   RN-15  la media del curso y el promedio ponderado por creditos NO se guardan:
--          se calculan con las dos consultas documentadas en modelo-datos.md §7 y
--          verificadas en db/verificacion/verificar_notas.sql
--
-- Requisito de esquema (D-14): `CREATE EXTENSION IF NOT EXISTS unaccent;` va en 01-schema.sql
-- porque la usan el buscador de estudiantes y el de matriculas. Esta migracion no la necesita,
-- pero la revision inicial de Alembic debe incluirla igual (si va solo en un lado, hay dos verdades).
-- ============================================================

-- ------------------------------------------------------------
-- TABLA: notas  (una nota cuelga de la MATRICULA, no del estudiante)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notas (
    id             integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id   integer      NOT NULL,
    tipo           varchar(15)  NOT NULL,
    numero         smallint     NOT NULL DEFAULT 1,
    nota           numeric(4,2) NOT NULL,
    fecha_registro date         NOT NULL DEFAULT CURRENT_DATE,
    observacion    varchar(200) NULL,
    creado_en      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT fk_notas_matricula
        FOREIGN KEY (matricula_id) REFERENCES matriculas (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_notas_matricula_tipo_numero UNIQUE (matricula_id, tipo, numero),
    CONSTRAINT ck_notas_tipo   CHECK (tipo IN ('practica', 'parcial', 'final')),
    CONSTRAINT ck_notas_nota   CHECK (nota >= 0 AND nota <= 20),
    CONSTRAINT ck_notas_numero CHECK (numero >= 1)
);

CREATE INDEX IF NOT EXISTS idx_notas_matricula ON notas (matricula_id);
-- Boleta (C-28): notas de un estudiante en un periodo, ordenadas por curso
CREATE INDEX IF NOT EXISTS idx_notas_orden      ON notas (matricula_id, tipo, numero);

COMMENT ON TABLE  notas IS 'Notas de una matricula. Nota vigesimal 0..20 (RN-16). Al borrar la matricula se borran (cascada, C-29)';
COMMENT ON COLUMN notas.tipo   IS 'practica | parcial | final (RN-16)';
COMMENT ON COLUMN notas.numero IS 'numero de la evaluacion dentro del tipo, desde 1';
COMMENT ON COLUMN notas.nota   IS '0.00 a 20.00, dos decimales (numeric(4,2) redondea lo que llegue con mas)';

-- ------------------------------------------------------------
-- RN-14: no se registran notas de una matricula retirada.
-- Aqui solo el INSERT: corregir una nota ya registrada de una matricula
-- que despues se retiro SI se permite (retirar no borra ni congela historial).
-- La API responde 409 antes de llegar; esto es la ultima linea de defensa.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_notas_matricula_activa() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT m.estado FROM matriculas m WHERE m.id = NEW.matricula_id) = 'retirado' THEN
        RAISE EXCEPTION
            'RN-14: no se registran notas de la matricula % porque esta retirada', NEW.matricula_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS tr_notas_matricula_activa ON notas;
CREATE TRIGGER tr_notas_matricula_activa
    BEFORE INSERT ON notas
    FOR EACH ROW EXECUTE FUNCTION fn_notas_matricula_activa();

-- ------------------------------------------------------------
-- VISTA: v_notas_detalle
-- La nota con su matricula, estudiante, curso y periodo (equivale a
-- v_matriculas_detalle pero del lado de las notas).
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW v_notas_detalle AS
SELECT
    n.id                      AS nota_id,
    n.matricula_id            AS matricula_id,
    m.periodo                 AS periodo,
    m.estado                  AS estado_matricula,
    m.estudiante_id           AS estudiante_id,
    e.codigo                  AS codigo_estudiante,
    (e.apellidos || ', ' || e.nombres) AS estudiante,
    m.curso_id                AS curso_id,
    c.codigo                  AS codigo_curso,
    c.nombre                  AS curso,
    c.creditos                AS creditos,
    n.tipo                    AS tipo,
    n.numero                  AS numero,
    n.nota                    AS nota,
    n.fecha_registro          AS fecha_registro,
    n.observacion             AS observacion
FROM notas n
INNER JOIN matriculas m  ON m.id = n.matricula_id
INNER JOIN estudiantes e ON e.id = m.estudiante_id
INNER JOIN cursos c      ON c.id = m.curso_id;

COMMENT ON VIEW v_notas_detalle IS
    'Notas con matricula, estudiante, curso y periodo. Base de la boleta (C-28) y de los promedios de RN-15.';
