"""esquema inicial: espejo exacto de db/init/*.sql

Revision ID: 0001_esquema_inicial
Revises:
Create Date: 21/09/2026 (Sprint 1)

GENERADO por backend/herramientas/generar_revision_inicial.py — NO editar a mano.
Fuente: db/init/01-schema.sql, 02-view.sql, 03-seed.sql, 04-notas.sql (autor @analista).

Incluye, como exige D-14:
  * CREATE EXTENSION IF NOT EXISTS unaccent  (sin ella C-08 es incumplible: BUG-07)
  * las 5 tablas (4 del legacy + notas), los CHECK/UNIQUE/FK y los índices
  * las 2 vistas: v_matriculas_detalle y v_notas_detalle
  * el trigger de RN-14 (no se califica una matrícula retirada)
  * los datos del seed (12 estudiantes / 7 cursos / 24 matrículas / 1 admin) con
    ON CONFLICT DO NOTHING y la sincronización de las secuencias IDENTITY

Así `alembic upgrade head` sobre una base limpia deja exactamente el mismo
esquema y los mismos datos que el volumen creado por db/init/.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "0001_esquema_inicial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (archivo de origen, sentencia SQL) — se ejecutan en el orden de db/init/
SENTENCIAS: list[tuple[str, str]] = [
    # --- 01-schema.sql (22 sentencias) ---
    (
        "01-schema.sql",
        r"""SET client_encoding = 'UTF8'""",
    ),
    (
        "01-schema.sql",
        r"""CREATE EXTENSION IF NOT EXISTS unaccent""",
    ),
    (
        "01-schema.sql",
        r"""CREATE TABLE IF NOT EXISTS usuarios (
    id              integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  varchar(50)  NOT NULL,
    email           varchar(100) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    nombre_completo varchar(100) NOT NULL,
    rol             varchar(20)  NOT NULL DEFAULT 'admin',
    estado          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_usuarios_nombre_usuario UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuarios_email          UNIQUE (email),
    CONSTRAINT ck_usuarios_rol            CHECK (rol IN ('admin', 'asistente')),
    CONSTRAINT ck_usuarios_usuario_formato
        CHECK (nombre_usuario ~ '^[A-Za-z0-9_.]{3,50}$'),
    CONSTRAINT ck_usuarios_email_formato
        CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT ck_usuarios_nombre_no_vacio CHECK (btrim(nombre_completo) <> '')
)""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON TABLE  usuarios IS 'Usuarios del sistema administrativo (login del panel)'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN usuarios.rol    IS 'admin | asistente'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN usuarios.estado IS 'true=activo, false=inactivo (no se puede desactivar el propio usuario)'""",
    ),
    (
        "01-schema.sql",
        r"""CREATE TABLE IF NOT EXISTS estudiantes (
    id               integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           varchar(20)  NOT NULL,
    dni              char(8)      NOT NULL,
    nombres          varchar(80)  NOT NULL,
    apellidos        varchar(80)  NOT NULL,
    email            varchar(100) NULL,
    telefono         varchar(20)  NULL,
    fecha_nacimiento date         NULL,
    direccion        varchar(150) NULL,
    estado           boolean      NOT NULL DEFAULT true,
    creado_en        timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_estudiantes_codigo UNIQUE (codigo),
    CONSTRAINT uq_estudiantes_dni    UNIQUE (dni),
    CONSTRAINT ck_estudiantes_dni    CHECK (dni ~ '^[0-9]{8}$'),
    CONSTRAINT ck_estudiantes_codigo_no_vacio  CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_estudiantes_nombres_no_vacio  CHECK (btrim(nombres) <> ''),
    CONSTRAINT ck_estudiantes_apellidos_no_vacio CHECK (btrim(apellidos) <> ''),
    CONSTRAINT ck_estudiantes_email
        CHECK (email IS NULL OR email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT ck_estudiantes_fecha_nacimiento
        CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento > DATE '1900-01-01')
)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_estudiantes_apellidos ON estudiantes (apellidos)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_estudiantes_nombres   ON estudiantes (nombres)""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN estudiantes.dni   IS '8 digitos, unico (RN-04)'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN estudiantes.estado IS 'true=activo (aparece en selectores), false=inactivo (baja logica)'""",
    ),
    (
        "01-schema.sql",
        r"""CREATE TABLE IF NOT EXISTS cursos (
    id          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(20)  NOT NULL,
    nombre      varchar(100) NOT NULL,
    descripcion text         NULL,
    creditos    smallint     NOT NULL DEFAULT 3,
    horas       smallint     NOT NULL DEFAULT 48,
    estado      boolean      NOT NULL DEFAULT true,
    creado_en   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_cursos_codigo UNIQUE (codigo),
    CONSTRAINT ck_cursos_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_cursos_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_cursos_creditos CHECK (creditos BETWEEN 1 AND 10),
    CONSTRAINT ck_cursos_horas    CHECK (horas BETWEEN 1 AND 1000)
)""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN cursos.creditos IS '1..10 (regla del legacy cursos/create.php)'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN cursos.horas    IS 'horas lectivas del curso, entero positivo'""",
    ),
    (
        "01-schema.sql",
        r"""CREATE TABLE IF NOT EXISTS matriculas (
    id              integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id   integer     NOT NULL,
    curso_id        integer     NOT NULL,
    periodo         varchar(7)  NOT NULL,
    fecha_matricula date        NOT NULL,
    estado          varchar(15) NOT NULL DEFAULT 'activa',
    creado_en       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_matriculas_estudiante
        FOREIGN KEY (estudiante_id) REFERENCES estudiantes (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_matriculas_curso
        FOREIGN KEY (curso_id) REFERENCES cursos (id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT uq_matriculas_estudiante_curso_periodo
        UNIQUE (estudiante_id, curso_id, periodo),
    CONSTRAINT ck_matriculas_periodo CHECK (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_matriculas_estado  CHECK (estado IN ('activa', 'retirado'))
)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_matriculas_estudiante ON matriculas (estudiante_id)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_matriculas_curso      ON matriculas (curso_id)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_matriculas_periodo    ON matriculas (periodo)""",
    ),
    (
        "01-schema.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_matriculas_fecha      ON matriculas (fecha_matricula DESC, id DESC)""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON TABLE  matriculas IS 'Matriculas: un estudiante en un curso, en un periodo (RN-08)'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN matriculas.periodo IS 'AAAA-MM, ej. 2026-02 (RN-06)'""",
    ),
    (
        "01-schema.sql",
        r"""COMMENT ON COLUMN matriculas.estado  IS 'activa | retirado (baja logica de la matricula, RN-07)'""",
    ),
    # --- 02-view.sql (2 sentencias) ---
    (
        "02-view.sql",
        r"""CREATE OR REPLACE VIEW v_matriculas_detalle AS
SELECT
    m.id                      AS matricula_id,
    m.periodo                 AS periodo,
    m.fecha_matricula         AS fecha_matricula,
    m.estado                  AS estado_matricula,
    e.id                      AS estudiante_id,
    e.codigo                  AS codigo_estudiante,
    e.dni                     AS dni,
    e.apellidos               AS apellidos_estudiante,
    e.nombres                 AS nombres_estudiante,
    (e.apellidos || ', ' || e.nombres) AS estudiante,
    e.email                   AS email_estudiante,
    c.id                      AS curso_id,
    c.codigo                  AS codigo_curso,
    c.nombre                  AS curso,
    c.creditos                AS creditos,
    c.horas                   AS horas
FROM matriculas m
INNER JOIN estudiantes e ON e.id = m.estudiante_id
INNER JOIN cursos c      ON c.id = m.curso_id""",
    ),
    (
        "02-view.sql",
        r"""COMMENT ON VIEW v_matriculas_detalle IS
    'Matriculas con datos del estudiante y del curso. Origen: legacy v_matriculas_detalle + columnas apellidos/nombres/email/horas para que el SPA ordene sin volver a consultar.'""",
    ),
    # --- 03-seed.sql (12 sentencias) ---
    (
        "03-seed.sql",
        r"""INSERT INTO usuarios (id, nombre_usuario, email, password_hash, nombre_completo, rol, estado) VALUES
(1, 'admin', 'admin@horizonte.edu.pe',
 '$2y$10$Tzgm/meEuR9o/nxq1ocKBu01ncP.pbnMay7a1aqWsuwXA4Q9Y9nzu',
 'Administrador del Sistema', 'admin', true)
ON CONFLICT DO NOTHING""",
    ),
    (
        "03-seed.sql",
        r"""INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, telefono, fecha_nacimiento, direccion) VALUES
( 1, 'E20260001', '45123456', 'Carlos Alberto',    'Ramírez Torres',     'cramirez@correo.pe',   '987654321', '2005-03-14', 'Av. Los Laureles 245, Lima'),
( 2, 'E20260002', '46234567', 'María Fernanda',    'Quispe Huamán',      'mquispe@correo.pe',    '986543210', '2006-07-22', 'Jr. Puno 118, Lima'),
( 3, 'E20260003', '47345678', 'Luis Enrique',      'Gutiérrez Salas',    'lgutierrez@correo.pe', '985432109', '2004-11-30', 'Calle Los Olivos 87, Callao'),
( 4, 'E20260004', '48456789', 'Ana Lucía',         'Vargas Mendoza',     'avargas@correo.pe',    '984321098', '2005-01-09', 'Av. Grau 456, Lima'),
( 5, 'E20260005', '49567890', 'Diego Antonio',     'Flores Chávez',      'dflores@correo.pe',    '983210987', '2006-05-18', 'Jr. Amazonas 332, Lima'),
( 6, 'E20260006', '50678901', 'Valeria Sofía',     'Paredes Rojas',      'vparedes@correo.pe',   '982109876', '2004-09-25', 'Av. Arequipa 1780, Lima'),
( 7, 'E20260007', '51789012', 'Jorge Luis',        'Castillo Neyra',     'jcastillo@correo.pe',  '981098765', '2005-12-03', 'Calle Los Pinos 51, Miraflores'),
( 8, 'E20260008', '52890123', 'Camila Andrea',     'Ríos Delgado',       'crios@correo.pe',      '980987654', '2006-02-27', 'Jr. Chiclayo 220, Lima'),
( 9, 'E20260009', '53901234', 'Miguel Ángel',      'Herrera Palacios',   'mherrera@correo.pe',   '979876543', '2004-06-11', 'Av. Universitaria 3120, Lima'),
(10, 'E20260010', '54012345', 'Nicole Alessandra', 'Torres Vega',        'ntorres@correo.pe',    '978765432', '2005-08-19', 'Calle El Sol 96, San Miguel'),
(11, 'E20260011', '55123456', 'Renato Gabriel',    'Salazar Meza',       'rsalazar@correo.pe',   '977654321', '2006-04-07', 'Jr. Cusco 154, Lima'),
(12, 'E20260012', '56234567', 'Fiorella Milagros', 'Cárdenas Ruiz',      'fcardenas@correo.pe',  '976543210', '2005-10-15', 'Av. La Marina 2890, Lima')
ON CONFLICT DO NOTHING""",
    ),
    (
        "03-seed.sql",
        r"""INSERT INTO cursos (id, codigo, nombre, descripcion, creditos, horas) VALUES
(1, 'C101', 'Matemática Básica',             'Fundamentos de aritmética, álgebra y geometría aplicada.', 4, 64),
(2, 'C102', 'Comunicación Efectiva',         'Redacción académica, expresión oral y comprensión lectora.', 3, 48),
(3, 'C201', 'Programación Web III',          'Desarrollo de aplicaciones web con PHP, MySQL y Bootstrap.', 4, 64),
(4, 'C202', 'Base de Datos II',              'Diseño y administración de bases de datos relacionales.', 3, 48),
(5, 'C203', 'Inglés Técnico',                'Inglés orientado al ámbito profesional y técnico.', 2, 32),
(6, 'C204', 'Estadística Aplicada',          'Estadística descriptiva e inferencial para la toma de decisiones.', 3, 48),
(7, 'C205', 'Fundamentos de Administración', 'Principios de gestión, organización y liderazgo.', 3, 48)
ON CONFLICT DO NOTHING""",
    ),
    (
        "03-seed.sql",
        r"""INSERT INTO matriculas (id, estudiante_id, curso_id, periodo, fecha_matricula, estado) VALUES
( 1,  1, 1, '2026-02', '2026-08-03', 'activa'),
( 2,  1, 2, '2026-02', '2026-08-03', 'activa'),
( 3,  2, 1, '2026-02', '2026-08-04', 'activa'),
( 4,  2, 3, '2026-02', '2026-08-04', 'activa'),
( 5,  3, 3, '2026-02', '2026-08-05', 'activa'),
( 6,  3, 4, '2026-02', '2026-08-05', 'activa'),
( 7,  4, 2, '2026-02', '2026-08-06', 'activa'),
( 8,  4, 5, '2026-02', '2026-08-06', 'activa'),
( 9,  5, 1, '2026-02', '2026-08-07', 'activa'),
(10,  5, 6, '2026-02', '2026-08-07', 'activa'),
(11,  6, 3, '2026-02', '2026-08-07', 'activa'),
(12,  6, 7, '2026-02', '2026-08-07', 'activa'),
(13,  7, 4, '2026-02', '2026-08-10', 'retirado'),
(14,  7, 5, '2026-02', '2026-08-10', 'activa'),
(15,  8, 2, '2026-02', '2026-08-11', 'activa'),
(16,  8, 6, '2026-02', '2026-08-11', 'activa'),
(17,  9, 1, '2026-02', '2026-08-12', 'activa'),
(18,  9, 7, '2026-02', '2026-08-12', 'activa'),
(19, 10, 3, '2026-02', '2026-08-13', 'activa'),
(20, 10, 5, '2026-02', '2026-08-13', 'activa'),
(21, 11, 2, '2026-02', '2026-08-14', 'activa'),
(22, 11, 4, '2026-02', '2026-08-14', 'activa'),
(23, 12, 1, '2026-02', '2026-08-17', 'activa'),
(24, 12, 6, '2026-02', '2026-08-17', 'activa')
ON CONFLICT DO NOTHING""",
    ),
    (
        "03-seed.sql",
        r"""SELECT setval(pg_get_serial_sequence('usuarios',   'id'), (SELECT max(id) FROM usuarios))""",
    ),
    (
        "03-seed.sql",
        r"""SELECT setval(pg_get_serial_sequence('estudiantes','id'), (SELECT max(id) FROM estudiantes))""",
    ),
    (
        "03-seed.sql",
        r"""SELECT setval(pg_get_serial_sequence('cursos',     'id'), (SELECT max(id) FROM cursos))""",
    ),
    (
        "03-seed.sql",
        r"""SELECT setval(pg_get_serial_sequence('matriculas', 'id'), (SELECT max(id) FROM matriculas))""",
    ),
    (
        "03-seed.sql",
        r"""ANALYZE usuarios""",
    ),
    (
        "03-seed.sql",
        r"""ANALYZE estudiantes""",
    ),
    (
        "03-seed.sql",
        r"""ANALYZE cursos""",
    ),
    (
        "03-seed.sql",
        r"""ANALYZE matriculas""",
    ),
    # --- 04-notas.sql (12 sentencias) ---
    (
        "04-notas.sql",
        r"""CREATE TABLE IF NOT EXISTS notas (
    id             integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id   integer      NOT NULL,
    tipo           varchar(15)  NOT NULL,
    numero         smallint     NOT NULL DEFAULT 1,
    nota           numeric(4,2) NOT NULL,
    fecha_registro date         NOT NULL DEFAULT CURRENT_DATE,
    observacion    varchar(200) NULL,
    creado_en      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT fk_notas_matricula
        FOREIGN KEY (matricula_id) REFERENCES matriculas (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_notas_matricula_tipo_numero UNIQUE (matricula_id, tipo, numero),
    CONSTRAINT ck_notas_tipo   CHECK (tipo IN ('practica', 'parcial', 'final')),
    CONSTRAINT ck_notas_nota   CHECK (nota >= 0 AND nota <= 20),
    CONSTRAINT ck_notas_numero CHECK (numero >= 1)
)""",
    ),
    (
        "04-notas.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_notas_matricula ON notas (matricula_id)""",
    ),
    (
        "04-notas.sql",
        r"""CREATE INDEX IF NOT EXISTS idx_notas_orden      ON notas (matricula_id, tipo, numero)""",
    ),
    (
        "04-notas.sql",
        r"""COMMENT ON TABLE  notas IS 'Notas de una matricula. Nota vigesimal 0..20 (RN-16). Al borrar la matricula se borran (cascada, C-29)'""",
    ),
    (
        "04-notas.sql",
        r"""COMMENT ON COLUMN notas.tipo   IS 'practica | parcial | final (RN-16)'""",
    ),
    (
        "04-notas.sql",
        r"""COMMENT ON COLUMN notas.numero IS 'numero de la evaluacion dentro del tipo, desde 1'""",
    ),
    (
        "04-notas.sql",
        r"""COMMENT ON COLUMN notas.nota   IS '0.00 a 20.00, dos decimales (numeric(4,2) redondea lo que llegue con mas)'""",
    ),
    (
        "04-notas.sql",
        r"""CREATE OR REPLACE FUNCTION fn_notas_matricula_activa() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT m.estado FROM matriculas m WHERE m.id = NEW.matricula_id) = 'retirado' THEN
        RAISE EXCEPTION
            'RN-14: no se registran notas de la matricula % porque esta retirada', NEW.matricula_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$""",
    ),
    (
        "04-notas.sql",
        r"""DROP TRIGGER IF EXISTS tr_notas_matricula_activa ON notas""",
    ),
    (
        "04-notas.sql",
        r"""CREATE TRIGGER tr_notas_matricula_activa
    BEFORE INSERT ON notas
    FOR EACH ROW EXECUTE FUNCTION fn_notas_matricula_activa()""",
    ),
    (
        "04-notas.sql",
        r"""CREATE OR REPLACE VIEW v_notas_detalle AS
SELECT
    n.id                      AS nota_id,
    n.matricula_id            AS matricula_id,
    m.periodo                 AS periodo,
    m.estado                  AS estado_matricula,
    m.estudiante_id           AS estudiante_id,
    e.codigo                  AS codigo_estudiante,
    (e.apellidos || ', ' || e.nombres) AS estudiante,
    m.curso_id                AS curso_id,
    c.codigo                  AS codigo_curso,
    c.nombre                  AS curso,
    c.creditos                AS creditos,
    n.tipo                    AS tipo,
    n.numero                  AS numero,
    n.nota                    AS nota,
    n.fecha_registro          AS fecha_registro,
    n.observacion             AS observacion
FROM notas n
INNER JOIN matriculas m  ON m.id = n.matricula_id
INNER JOIN estudiantes e ON e.id = m.estudiante_id
INNER JOIN cursos c      ON c.id = m.curso_id""",
    ),
    (
        "04-notas.sql",
        r"""COMMENT ON VIEW v_notas_detalle IS
    'Notas con matricula, estudiante, curso y periodo. Base de la boleta (C-28) y de los promedios de RN-15.'""",
    ),
]


def upgrade() -> None:
    for origen, sentencia in SENTENCIAS:
        op.execute(sentencia)


def downgrade() -> None:
    """Baja explícita: el esquema del legacy no tiene datos que conservar."""
    op.execute("DROP TRIGGER IF EXISTS tr_notas_matricula_activa ON notas")
    op.execute("DROP FUNCTION IF EXISTS fn_notas_matricula_activa()")
    op.execute("DROP VIEW IF EXISTS v_notas_detalle")
    op.execute("DROP VIEW IF EXISTS v_matriculas_detalle")
    op.execute("DROP TABLE IF EXISTS notas")
    op.execute("DROP TABLE IF EXISTS matriculas")
    op.execute("DROP TABLE IF EXISTS cursos")
    op.execute("DROP TABLE IF EXISTS estudiantes")
    op.execute("DROP TABLE IF EXISTS usuarios")
    op.execute("DROP EXTENSION IF EXISTS unaccent")
